# Generated by Django 3.2.9 on 2022-02-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoF', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/static/img/img_no_disponible.png', null=True, upload_to='imagenesProductos/'),
        ),
    ]
