# Generated by Django 3.2.9 on 2022-02-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoF', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Sin Descripcion', max_length=100),
        ),
    ]
